### ISSUE TITLE
profile_scrape() doesn't work

### ISSUE THREAD

**Issue by ruizuo11** [Bishwas-py/fiverr-scraping-api#1]
Hi Bishwas, 

Thank you so much for this package! I'm wiring b/c the scraper.profile_scrape() does not work even though I do exactly as the sample code said. The error message is:
_AttributeError: 'NoneType' object has no attribute 'text'_

And is seems that this line of code goes wrong:
_bio = oneliner.find('small', {'class': 'oneliner'}).text_

However, I wasn't able to find what was wrong with this script. Would you mind providing some clues?

Bests,
Rui

**Comment by ruizuo11** [comment]
Problem solved. The bio was not in _oneliner_ but in _profile_. Change the line
 _bio = oneliner.find('small', {'class': 'oneliner'}).text_ 
to
_bio = profile.find('div', {'class': 'description'}).text_ 
and everything works out.

**Comment by Bishwas-py** [comment]
@ruizuo11 The issue has been resolved in the [new update](https://pypi.org/project/fiverr-api/#:~:text=Change%20user%2Dagent%20or%20other%20headers.).
