### ISSUE TITLE
It seem not working

### ISSUE THREAD

**Issue by south1907** [Bishwas-py/fiverr-scraping-api#3]
It seem not working because Fiverr.com detect it is not allowed

I run example code, and throw error:

`File "/Users/heva/Desktop/research/fiverr/test.py", line 14, in <module>
    gig_data = scraper.gig_scrape(gig_url)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/fiverr_api.py", line 56, in gig_scrape
    categories_breadcrumbs_html
UnboundLocalError: local variable 'categories_breadcrumbs_html' referenced before assignment
`

**Comment by Bishwas-py** [comment]
Can me share your URL please?

**Comment by Bishwas-py** [comment]
Also, the code?

**Comment by Bishwas-py** [comment]
@south1907 The issue has been resolved in the [new update](https://pypi.org/project/fiverr-api/#:~:text=Change%20user%2Dagent%20or%20other%20headers.).
