### ISSUE TITLE
NonType object issue

### ISSUE THREAD

**Issue by jayvs6341** [Bishwas-py/fiverr-scraping-api#4]
Traceback (most recent call last):
  File "/home/jay/.local/lib/python3.8/site-packages/fiverr_api.py", line 53, in gig_scrape
    categories_breadcrumbs_html = gig_overview.find(
AttributeError: 'NoneType' object has no attribute 'find'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "fiverr.py", line 13, in <module>
    gig_data = scraper.gig_scrape(gig_url)
  File "/home/jay/.local/lib/python3.8/site-packages/fiverr_api.py", line 56, in gig_scrape
    categories_breadcrumbs_html
UnboundLocalError: local variable 'categories_breadcrumbs_html' referenced before assignment

**Comment by Bishwas-py** [comment]
@jayvs6341 I'll have a look at it ASAP.

**Comment by Bishwas-py** [comment]
@jayvs6341  The issue has been resolved in the [new update](https://pypi.org/project/fiverr-api/#:~:text=Change%20user%2Dagent%20or%20other%20headers.).

**Comment by Bishwas-py** [comment]
@jayvs6341 Please use the new code. The issue has been fixed, I believe. I am marking this as closed for now.

For scraping Fiverr profiles.
```python
from fiverr_api.scrapers import profile_scrape

# URL of the Fiverr profile you want to scrape
profile_url = "https://www.fiverr.com/some-seller"

# Scrape profile data
profile_data = profile_scrape(profile_url)

# Print the scraped profile data
print(profile_data)
```

[Read this](https://pypi.org/project/fiverr-api/#:~:text=(profile_data)-,Proxy%20Support,-You%20can%20use) to use proxies or change headers.
