### ISSUE TITLE
UnboundLocalError: local variable 'categories_breadcrumbs_html' referenced before assignment

### ISSUE THREAD

**Issue by MatteoSchifano** [Bishwas-py/fiverr-scraping-api#5]
Hi, 
I encountered an issue while using the provided base code from the developer in the library, which resulted in an "UnboundLocalError: local variable 'categories_breadcrumbs_html' referenced before assignment" error.
Can you help me? Thanks

**Comment by Bishwas-py** [comment]
@MatteoSchifano  The issue has been resolved in the [new update](https://pypi.org/project/fiverr-api/#:~:text=Change%20user%2Dagent%20or%20other%20headers.).
