### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'findChild'

### ISSUE THREAD

**Issue by toffuffee** [Bishwas-py/fiverr-scraping-api#6]
Clearly following your instructions, your library does not work, although all dependencies are installed
Error: 
![image](https://github.com/Bishwas-py/fiverr-scraping-api/assets/116083824/103d47d7-0a97-4f6a-a9c2-ddf5c0677693)

**Comment by toffuffee** [comment]
Code: 

from fiverr_api.scrapers import gig_scrape, profile_scrape
gig_url = "https://www.fiverr.com/otem_global/your-kajabi-teachable-website-expert-fix-your-pipeline-set-up-online-courses"
profile_url = "https://www.fiverr.com/otem_global/"
gig_data = gig_scrape(gig_url)
profile_data = profile_scrape(profile_url)
print(gig_data)
print(profile_data)`

**Comment by toffuffee** [comment]
This is very strange, although if you do the import like this:

`from fiverr_api import scrapers`

And call methods like this:

`gig_data = scrapers.gig_scrape(gig_url)`
`profile_data = scrapers.profile_scrape(profile_url)`

Then everything works as it should

**Comment by Bishwas-py** [comment]
> Clearly following your instructions, your library does not work, although all dependencies are installed Error: ![image](https://user-images.githubusercontent.com/116083824/276551889-103d47d7-0a97-4f6a-a9c2-ddf5c0677693.png)

This might be an issue because of the IP blocking from Fiverr. You can use proxies.
