### ISSUE TITLE
New questions about profile_scrape

### ISSUE THREAD

**Issue by wuchuanshiqi** [Bishwas-py/fiverr-scraping-api#7]
![屏幕截图 2024-01-03 191850](https://github.com/Bishwas-py/fiverr-scraping-api/assets/155530897/f661e7d9-bdf2-42a7-9b38-a4ac32d237d5)
![屏幕截图 2024-01-03 191812](https://github.com/Bishwas-py/fiverr-scraping-api/assets/155530897/60215f83-58e0-41bf-940d-e1a20e986224)
As shown in the figure above, I have set up the proxy, but there is still an error. I sincerely hope to get your correction, thank you very much!

**Comment by Bishwas-py** [comment]
This code is now outdated.
